# Generated by Django 5.2.15 on 2026-06-06 08:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=255)),
                ('endereco_empresa', models.CharField(max_length=255)),
                ('tipo_denuncia', models.CharField(choices=[('ASSEDIO', 'ASSÉDIO (MORAL, SEXUAL, ETC.)'), ('DISCRIMINACAO', 'DISCRIMINAÇÃO (RAÇA, GÊNERO, IDADE, ETC.)'), ('VIOLACAO', 'VIOLAÇÕES DE POLÍTICAS DA EMPRESA'), ('SEGURANCA', 'QUESTÕES DE SEGURANÇA NO TRABALHO'), ('OUTROS', 'OUTRAS QUESTÕES ESPECÍFICAS')], max_length=13)),
                ('descricao', models.TextField()),
                ('testemunhas', models.CharField(blank=True, max_length=255, null=True)),
                ('acoes', models.CharField(blank=True, max_length=255, null=True)),
                ('anonimo', models.BooleanField(default=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('data_ocorrido', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('protocolo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('situacao', models.BooleanField(default=True)),
                ('resposta', models.TextField(blank=True, null=True)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Denuncia', to='core.cidades')),
            ],
        ),
        migrations.AddField(
            model_name='cidades',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estado'),
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='denuncia_images')),
                ('denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.denuncia')),
            ],
        ),
    ]
