# Generated by Django 5.2.16 on 2026-08-01 04:59
from django.contrib.postgres.operations import TrigramExtension
from django.contrib.postgres.operations import UnaccentExtension
import django.contrib.postgres.indexes
from django.db import migrations
import csv
from django.conf import settings
import os


def popular_cidades_estados(apps, schema_editor):
    """
    Popula Estados e Cidades a partir do CSV de forma ultra-rápida e idempotente.
    Usa apps.get_model para pegar o modelo histórico (compatível com migrações).
    """
    Estado = apps.get_model('core', 'Estado')
    Cidade = apps.get_model('core', 'Cidades')

    csv_path = os.path.join(settings.BASE_DIR, 'data/Municipios_normalizados.csv')

    if not os.path.exists(csv_path):
        alt_path = '/app/data/Municipios_normalizados.csv'
        if os.path.exists(alt_path):
            csv_path = alt_path
        else:
            print(f"AVISO: CSV não encontrado em {csv_path}. Pulando população.")
            return
    
    print("Iniciando importação de Estados e Cidades...")

    estados_cache = {}
    cidades_para_criar = []
    cidades_existentes = set(Cidade.objects.values_list('nome', 'estado__uf'))

    with open(csv_path, 'r', encoding='latin-1') as f:
        reader = csv.DictReader(f)
        for row in reader:
            uf = row['Chave'].strip()
            if uf not in estados_cache:
                estado, _ = Estado.objects.get_or_create(uf=uf)
                estados_cache[uf] = estado
            else:
                estado = estados_cache[uf]

            nomes_cidades = [c.strip() for c in row['Valores'].split(',') if c.strip()]
            for cidade_nome in nomes_cidades:
                if (cidade_nome, uf) not in cidades_existentes:
                    cidades_para_criar.append(Cidade(nome=cidade_nome, estado=estado))
                    cidades_existentes.add((cidade_nome, uf))
    
    if cidades_para_criar:
        Cidade.objects.bulk_create(cidades_para_criar, ignore_conflicts=True)
    
    print("Importação concluída.")
    


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        TrigramExtension(),
        UnaccentExtension(),
        migrations.AddIndex(
            model_name='denuncia',
            index=django.contrib.postgres.indexes.GinIndex(fields=['nome_empresa'], name='nome_empresa_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='cidades',
            index=django.contrib.postgres.indexes.GinIndex(fields=['nome'], name='nome_cidade_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.RunPython(popular_cidades_estados, reverse_code=migrations.RunPython.noop),

    ]
