# Generated by Django 5.2.16 on 2026-08-01 09:34

from django.db import migrations
import csv
from django.conf import settings
import os

def popular_cidades_estados(apps, schema_editor):
    """
    Popula Estados e Cidades a partir do CSV.
    Usa apps.get_model para pegar o modelo histórico (compatível com migrações antigas).
    """
    Estado = apps.get_model('core', 'Estado')
    Cidade = apps.get_model('core', 'Cidades')

    csv_path = os.path.join(settings.BASE_DIR, 'Municipios_normalizados.csv')

    if not os.path.exists(csv_path):
           print(f"AVISO: CSV não encontrado em {csv_path}. Pulando população.")
           return
    
    print("Iniciando importação de Estados e Cidades...")

    estados_cache = {}
    with open(csv_path, 'r', encoding='latin-1',) as f:
        reader = csv.DictReader(f)
        for row in reader:
            uf = row['Chave'].strip()
            nome_cidade = [cidade.strip() for cidade in row['Valores'].split(',')]
            if uf not in estados_cache:
                estado, _= Estado.objects.get_or_create(uf=uf)
                estados_cache[uf] = estado
            else:
                estado = estados_cache[uf]

            for cidade_nome in nome_cidade:
                Cidade.objects.get_or_create(nome=cidade_nome, estado=estado)
                
     # Get or Create Cidade
    
        print("Importação concluída.")
    

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_denuncia_nome_empresa_trgm_idx'),
    ]

    operations = [
        migrations.RunPython(popular_cidades_estados, reverse_code=migrations.RunPython.noop),
    ]
